apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  components:
    runner:
      # secret name for the runner image, if using private registry
      imagePullSecrets:
      - name: docker-vendor
  # It can be active/stop
  engineState: 'active'
  auxiliaryAppInfo: ''
  chaosServiceAccount: docker-service-kill-sa
  experiments:
    - name: docker-service-kill
      spec:
        components:
          experimentImagePullSecrets:
          - name: docker-vendor
        # nodeSelector: 
        #   # provide the node labels
        #   kubernetes.io/hostname: 'node02'
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '90' # in seconds
              
            - name: TARGET_NODE
              value: ''
              
            - name: LIB_IMAGE
              value: 'scbs.jfrog.io/docker-remote/chaosnative/go-runner:2.8.0'